backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'public/assets/uploads'
public_folder: '/assets/uploads'
collections:
  - name: 'careers'
    label: 'Careers'
    create: true
    folder: 'src/pages/posts/careers'
    slug: '{{year}}-{{month}}-{{day}}-{{fields.title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'court'
    label: 'Courts'
    create: true
    folder: 'src/pages/posts/courts'
    slug: '{{year}}-{{month}}-{{day}}-{{fields.name}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {
          label: 'Featured Image',
          name: 'image',
          widget: 'image',
          choose_url: true,
        }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Subname', name: 'subname', widget: 'string' }
      - { label: 'Posicao', name: 'position', widget: 'number' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Artist', name: 'artist', widget: 'string' }
      - { label: 'Duration', name: 'duration', widget: 'string' }
      - { label: 'partner', name: 'partner', widget: 'list', allow_add: true }
      - { label: 'What we Did', name: 'whaWeDid', widget: 'text' }
      - {
          label: 'Gallery',
          name: 'galleryImages',
          widget: 'list',
          field: { label: Image, name: image, widget: image },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'articles'
    label: 'Articles'
    create: true
    publish_mode: editorial_workflow
    folder: 'src/pages/posts/articles'
    slug: '{{year}}-{{month}}-{{day}}-{{fields.title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Subtitle', name: 'subname', widget: 'text' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'date',
          format: 'MMM Do YY',
          required: true,
        }
      - {
          label: 'Banner',
          name: 'image',
          widget: 'image',
          choose_url: true,
          required: true,
        }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'string',
          default: '../../../Layout/single-article.astro',
        }
  - name: 'esports'
    label: 'Esports'
    create: true
    publish_mode: editorial_workflow
    folder: 'src/pages/posts/esports'
    slug: '{{year}}-{{month}}-{{day}}-{{fields.title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Subtitle', name: 'subname', widget: 'text' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'date',
          format: 'MMM Do YY',
          required: true,
        }
      - {
          label: 'Banner',
          name: 'image',
          widget: 'image',
          choose_url: true,
          required: true,
        }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'string',
          default: '../../../Layout/single-article.astro',
        }
  - name: 'frontpage'
    label: 'Front Page'
    folder: 'src/pages/posts/frontpage'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {
          label: 'court image',
          name: 'courtImage',
          widget: 'image',
          choose_url: true,
          required: true,
        }
      - { label: 'Court Description', name: 'courtDescription', widget: 'text' }

      - { label: 'Product Name', name: 'productName', widget: 'string' }
      - { label: 'Product Price', name: 'productPrice', widget: 'number' }
      - {
          label: 'Product Description',
          name: 'productDescription',
          widget: 'text',
        }
      - {
          label: 'Product image',
          name: 'productImage',
          widget: 'image',
          choose_url: true,
          required: true,
        }
      - { label: 'Product Link', name: 'productLink', widget: 'string' }
  - name: 'summergallery'
    label: 'Summerleague Gallery'
    create: true
    folder: 'src/pages/posts/summergallery'
    slug: '{{year}}-{{month}}-{{day}}-{{fields.title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: Cover, name: cover, widget: image }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'date',
          format: 'YYYY MM DD H:M:S',
          required: true,
        }
      - label: 'Gallery'
        name: 'galleryImages'
        widget: 'list'
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Image description, name: description, widget: text }
          - { label: Credito, name: credito, widget: text }
  - name: 'summerarticles'
    label: 'Summer league Articles'
    create: true
    publish_mode: editorial_workflow
    folder: 'src/pages/posts/summerarticles'
    slug: '{{year}}-{{month}}-{{day}}-{{fields.title}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Subtitle', name: 'subname', widget: 'text' }
      - {
          label: 'Featured',
          name: 'featured',
          widget: 'boolean',
          default: false,
        }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'date',
          format: 'MMM Do YY',
          required: true,
        }
      - {
          label: 'Banner',
          name: 'image',
          widget: 'image',
          choose_url: true,
          required: true,
        }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'string',
          default: '../../../Layout/single-article.astro',
        }
  - name: 'summergames'
    label: 'Summer league Games'
    create: true
    publish_mode: editorial_workflow
    folder: 'src/pages/posts/summergames'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Team A', name: 'teamA', widget: 'string', required: true }
      - { label: 'Team B', name: 'teamB', widget: 'string', required: true }
      - {
          label: 'Location',
          name: 'location',
          widget: 'string',
          required: true,
        }
      - {
          label: 'Game time',
          name: 'time',
          widget: 'datetime',
          default: '',
          date_format: 'DD/MM',
          time_format: 'HH:mm',
          format: 'LLL',
          picker_utc: false,
          required: true,
        }
  - name: 'nft'
    label: 'NFT'
    create: true
    folder: 'src/pages/posts/nft'
    slug: '{{year}}-{{month}}-{{day}}-{{fields.dropname}}' # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - { label: 'Dropname', name: 'dropname', widget: 'string', required: true }
      - { label: Cover, name: cover, widget: image }
      - {
          label: 'Publish Date',
          name: 'publishDate',
          widget: 'date',
          format: 'YYYY MM DD H:M:S',
          required: true,
        }
      - label: 'Gallery'
        name: 'galleryImages'
        widget: 'list'
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Image description, name: description, widget: text }
          - { label: Credito, name: credito, widget: text }
          - { label: Price, name: price, widget: text }

