# .github/workflows/schedule-netlify-build.yml

name: Netlify Rebuild
on:
  schedule:
    # Customize schedule expression at crontab.guru
    # This one runs at 800 UTC daily
    - cron: '*/5 * * * *'
jobs:
  build:
    name: Netlify Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6175873c607d20bb32e8b4db
